entryPoints:
  web:
    address: ":80"

api:
  dashboard: true
  debug: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: traefik-proxy
    watch: true
    exposedByDefault: false